version: "3"

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
  db:
    
    build: ./mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=posse
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d

      # mysqlの=sqlを実行したかったら。。
